# Arquivo 01 - Cápitulo 2

## Instalando as bibliotecas necessárias

In [35]:
# Verificar versão Python utilizada para rodar o script:
from platform import python_version
print('Versão Python:', python_version())

Versão Python: 3.11.1


In [36]:
# Instalar o pacote 'watermark'
!pip install -q -U watermark
# ! para rodar no terminal, -q para não mostrar a instalação, -U para atualizar


[notice] A new release of pip is available: 23.2.1 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip


In [37]:
# Carregar bibliotecas necessárias
import numpy as np
print("Bibliotecas carregadas com sucesso!")

Bibliotecas carregadas com sucesso!


In [38]:
# Versões utilizadas neste jupyter notebook
# carregar a extensão:
%reload_ext watermark
# imprimir versões dos pacotes utilizados:
%watermark -a "gustavogzr" --iversions

Author: gustavogzr

numpy: 1.25.2



## Criando estruturas de dados NumPy

In [39]:
array1 = np.array([10,20,30,40]) # criando um array
print(array1) # imprimindo o array

[10 20 30 40]


In [40]:
array1.shape # verificando a forma do array

(4,)

In [41]:
array1.ndim # verificando a dimensão do array

1

In [42]:
# Criando um array bidimensional:
array2 = np.array([[100,83,15], [42,78,0]]) # criando um array bidimensional
print(array2) # imprimindo o array

[[100  83  15]
 [ 42  78   0]]


In [43]:
array2.shape # verificando a forma do array

(2, 3)

In [44]:
array2.ndim # verificando a dimensão do array

2

## Em Python tudo é Objeto, com Métodos e Atributos

Método - realiza ação no objeto

Atributo - característica do objeto

In [45]:
# Método:
array2.max() # valor máximo do array

100

In [46]:
# Atributo:
array2.ndim # dimensão do array

2

## Criando Estruturas de Dados com Arange

In [47]:
array3 = np.arange(15) # criando um array com 15 elementos
print(array3) # imprimindo o array

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [48]:
array4 = np.arange(0, 15, 3) # criando um array com elementos de 0 a 15, com passo de 3. 15 não é incluído.
print(array4) # imprimindo o array

[ 0  3  6  9 12]


## Criando Estruturas de Dados com Linspace

In [49]:
array5 = np.linspace(0, 3, 4) # criando um array com 4 elementos, de 0 a 3.
print(array5) # imprimindo o array

[0. 1. 2. 3.]


## Criando Estruturas de Dados com Outras Funções

In [50]:
array6 = np.zeros((10,8)) # criando um array de zeros, com 10 linhas e 8 colunas
array6 # imprimindo o array

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [51]:
array7 = np.ones((2,3,2)) # criando um array de uns, com 2 matrizes de 3 linhas e 2 colunas
array7 # imprimindo o array

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [52]:
array8 = np.eye(3) # criando uma matriz identidade 3x3
array8 # imprimindo o array

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [53]:
array9 = np.diag((2,1,4,6)) # criando uma matriz diagonal
array9 # imprimindo o array

array([[2, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 4, 0],
       [0, 0, 0, 6]])

In [54]:
np.random.seed(100) # definindo uma semente para reprodução dos resultados
array10 = np.random.rand(5) # criando um array com 5 elementos aleatórios
array10 # imprimindo o array

array([0.54340494, 0.27836939, 0.42451759, 0.84477613, 0.00471886])

In [55]:
array11 = np.random.randn(5) # criando um array com 5 elementos aleatórios, seguindo uma distribuição normal
array11 # imprimindo o array

array([ 0.35467445, -0.78606433, -0.2318722 ,  0.20797568,  0.93580797])

In [56]:
array12 = np.empty((3,2)) # criando um array vazio, com 3 linhas e 2 colunas
array12 # imprimindo o array

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [57]:
np.array([[9,4],[3,7]]) # criando um array bidimensional

array([[9, 4],
       [3, 7]])

In [58]:
np.tile(np.array([[9,4],[3,7]]), 4) # criando um array com 4 repetições do array bidimensional

array([[9, 4, 9, 4, 9, 4, 9, 4],
       [3, 7, 3, 7, 3, 7, 3, 7]])

In [59]:
np.tile(np.array([[9,4],[3,7]]), (2,2)) # criando um array com 2 repetições do array bidimensional

array([[9, 4, 9, 4],
       [3, 7, 3, 7],
       [9, 4, 9, 4],
       [3, 7, 3, 7]])