# Arquivo 01 - Cápitulo 02

## Instalando as bibliotecas necessárias

In [62]:
# Verificar versão Python utilizada para rodar o script:
from platform import python_version
print('Versão Python:', python_version())

Versão Python: 3.11.1


In [63]:
# Instalar o pacote 'watermark'
!pip install -q -U watermark
# ! para rodar no terminal, -q para não mostrar a instalação, -U para atualizar


[notice] A new release of pip is available: 23.2.1 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip


In [64]:
# Carregar bibliotecas necessárias
import numpy as np
print("Bibliotecas carregadas com sucesso!")

Bibliotecas carregadas com sucesso!


In [65]:
# Versões utilizadas neste jupyter notebook
# carregar a extensão:
%reload_ext watermark
# imprimir versões dos pacotes utilizados:
%watermark -a "gustavogzr" --iversions

Author: gustavogzr

numpy: 1.25.2



## Criando estruturas de dados NumPy

In [66]:
array1 = np.array([10,20,30,40]) # criando um array
print(array1) # imprimindo o array

[10 20 30 40]


In [67]:
array1.shape # verificando a forma do array

(4,)

In [68]:
array1.ndim # verificando a dimensão do array

1

In [69]:
# Criando um array bidimensional:
array2 = np.array([[100,83,15], [42,78,0]]) # criando um array bidimensional
print(array2) # imprimindo o array

[[100  83  15]
 [ 42  78   0]]


In [70]:
array2.shape # verificando a forma do array

(2, 3)

In [71]:
array2.ndim # verificando a dimensão do array

2

## Em Python tudo é Objeto, com Métodos e Atributos

Método - realiza ação no objeto

Atributo - característica do objeto

In [72]:
# Método:
array2.max() # valor máximo do array

100

In [73]:
# Atributo:
array2.ndim # dimensão do array

2

## Criando Estruturas de Dados com Arange

In [74]:
array3 = np.arange(15) # criando um array com 15 elementos
print(array3) # imprimindo o array

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [75]:
array4 = np.arange(0, 15, 3) # criando um array com elementos de 0 a 15, com passo de 3. 15 não é incluído.
print(array4) # imprimindo o array

[ 0  3  6  9 12]


## Criando Estruturas de Dados com Linspace

In [76]:
array5 = np.linspace(0, 3, 4) # criando um array com 4 elementos, de 0 a 3.
print(array5) # imprimindo o array

[0. 1. 2. 3.]


## Criando Estruturas de Dados com Outras Funções

In [77]:
array6 = np.zeros((10,8)) # criando um array de zeros, com 10 linhas e 8 colunas
array6 # imprimindo o array

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [78]:
array7 = np.ones((2,3,2)) # criando um array de uns, com 2 matrizes de 3 linhas e 2 colunas
array7 # imprimindo o array

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [79]:
array8 = np.eye(3) # criando uma matriz identidade 3x3
array8 # imprimindo o array

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [80]:
array9 = np.diag((2,1,4,6)) # criando uma matriz diagonal
array9 # imprimindo o array

array([[2, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 4, 0],
       [0, 0, 0, 6]])

In [81]:
np.random.seed(100) # definindo uma semente para reprodução dos resultados
array10 = np.random.rand(5) # criando um array com 5 elementos aleatórios
array10 # imprimindo o array

array([0.54340494, 0.27836939, 0.42451759, 0.84477613, 0.00471886])

In [82]:
array11 = np.random.randn(5) # criando um array com 5 elementos aleatórios, seguindo uma distribuição normal
array11 # imprimindo o array

array([ 0.35467445, -0.78606433, -0.2318722 ,  0.20797568,  0.93580797])

In [83]:
array12 = np.empty((3,2)) # criando um array vazio, com 3 linhas e 2 colunas
array12 # imprimindo o array

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [84]:
np.array([[9,4],[3,7]]) # criando um array bidimensional

array([[9, 4],
       [3, 7]])

In [85]:
np.tile(np.array([[9,4],[3,7]]), 4) # criando um array com 4 repetições do array bidimensional

array([[9, 4, 9, 4, 9, 4, 9, 4],
       [3, 7, 3, 7, 3, 7, 3, 7]])

In [86]:
np.tile(np.array([[9,4],[3,7]]), (2,2)) # criando um array com 2 repetições do array bidimensional

array([[9, 4, 9, 4],
       [3, 7, 3, 7],
       [9, 4, 9, 4],
       [3, 7, 3, 7]])

## Tipos de dados NumPy

In [87]:
array13 = np.array([8,-3,5,9], dtype='float') # criando um array com elementos float
array13 # imprimindo o array

array([ 8., -3.,  5.,  9.])

In [88]:
array13.dtype # verificando o tipo dos elementos do array

dtype('float64')

In [89]:
array14 = np.array([2,4,6,8]) # criando um array de inteiros
array14 # imprimindo o array

array([2, 4, 6, 8])

In [90]:
array14.dtype # verificando o tipo dos elementos do array

dtype('int32')

In [91]:
array15 = np.array([2.0,4,6,8]) # criando um array com elementos float e inteiros. Todos os elementos são float.
array15 # imprimindo o array

array([2., 4., 6., 8.])

In [92]:
array15.dtype # verificando o tipo dos elementos do array

dtype('float64')

In [93]:
array16 = np.array(['Data', 'Science', 'Academy']) # criando um array com strings
array16 # imprimindo o array

array(['Data', 'Science', 'Academy'], dtype='<U7')

In [94]:
array16.dtype # verificando o tipo dos elementos do array. <U7 significa unicode de até 7 caracteres.

dtype('<U7')

In [95]:
array17 = np.array([True, False, True]) # criando um array com booleanos
array17 # imprimindo o array

array([ True, False,  True])

In [96]:
array17.dtype # verificando o tipo dos elementos do array

dtype('bool')

In [97]:
array18 = np.array([7,-3,5.24]) # criando um array com elementos inteiros e float
array18 # imprimindo o array

array([ 7.  , -3.  ,  5.24])

In [98]:
array18.dtype # verificando o tipo dos elementos do array

dtype('float64')

In [99]:
array18.astype(int) # convertendo os elementos do array para inteiros

array([ 7, -3,  5])

## Operações com Arrays em NumPy

In [100]:
array19 = np.arange(0, 30) * 5 # criando um array com elementos de 0 a 30, multiplicados por 5
array19 # imprimindo o array

array([  0,   5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,
        65,  70,  75,  80,  85,  90,  95, 100, 105, 110, 115, 120, 125,
       130, 135, 140, 145])

In [101]:
array20 = np.arange(5) ** 4 # criando um array com elementos de 0 a 5, elevados a 4
array20 # imprimindo o array

array([  0,   1,  16,  81, 256], dtype=int32)

In [102]:
array21 = np.arange(0, 30) + 1 # criando um array com elementos de 0 a 30, somados a 1
array21 # imprimindo o array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [103]:
array22 = np.arange(0, 30, 3) + 3 # criando um array com elementos de 0 a 30, com passo de 3, somados a 3
array22 # imprimindo o array

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [104]:
array23 = np.arange(1, 11) # criando um array com elementos de 1 a 10
array23 # imprimindo o array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [105]:
array22 - array23 # subtraindo os elementos do array22 pelos elementos do array23

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [106]:
array22 + array23 # somando os elementos do array22 com os elementos do array23

array([ 4,  8, 12, 16, 20, 24, 28, 32, 36, 40])

In [107]:
array22 / array23 # dividindo os elementos do array22 pelos elementos do array23

array([3., 3., 3., 3., 3., 3., 3., 3., 3., 3.])

In [108]:
array22 * array23 # multiplicando os elementos do array22 pelos elementos do array23

array([  3,  12,  27,  48,  75, 108, 147, 192, 243, 300])

In [109]:
array22 > array23 # verificando se os elementos do array22 são maiores que os elementos do array23

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [110]:
arr1 = np.array([True, False, True, False]) # criando um array com booleanos
arr2 = np.array([False, False, True, False]) # criando um array com booleanos
np.logical_and(arr1, arr2) # verificando se os elementos dos arrays são True

array([False, False,  True, False])

In [111]:
np.logical_or(arr1, arr2) # verificando se algum dos elementos dos arrays é True

array([ True, False,  True, False])

## Podemos criar arrays com Python puro (sem usar a biblioteca NumPy). Porém, a biblioteca NumPy é otimizada para operações com arrays, sendo muito mais rápida que o Python puro.

In [112]:
array_numpy = np.arange(1000) # criando um array com 1000 elementos
%timeit array_numpy ** 4 
# calculando o tempo de execução para elevar os elementos do array a 4. O comando %timeit é utilizado para medir o tempo de execução de uma linha de código.

3.24 µs ± 291 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [113]:
array_python = range(1000) # criando um range com 1000 elementos
%timeit [array_python[i] ** 4 for i in array_python]

102 µs ± 4.75 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)
