# Cápitulo 02 - Arquivo 03

In [55]:
# Importando bibliotecas e imprimir versão:
from platform import python_version
print('Versão Python:', python_version(), '\n')

import numpy as np

%reload_ext watermark
%watermark -a "gustavogzr" --iversions

Versão Python: 3.11.1 

Author: gustavogzr

numpy: 1.25.2



## Transposição e Reshaping de Arrays

In [56]:
array1 = np.array([[65,23,19],[41,87,10]]) # Criando um array 2D
array1 # Exibindo o array

array([[65, 23, 19],
       [41, 87, 10]])

In [57]:
array1.T # Transpondo o array

array([[65, 41],
       [23, 87],
       [19, 10]])

In [58]:
np.transpose(array1) # Transpondo o array

array([[65, 41],
       [23, 87],
       [19, 10]])

## Broadcasting - Operações entre Arrays de Tamanhos Diferentes

In [59]:
array2 = np.array([[33,34,35]]) # Criando um array
array2 # Exibindo o array

array([[33, 34, 35]])

In [60]:
array2.T # Transpondo o array

array([[33],
       [34],
       [35]])

In [61]:
array2.T + array2 # Somando o array transposto com o array original

array([[66, 67, 68],
       [67, 68, 69],
       [68, 69, 70]])

## Transformando Matrizes em Vetores

In [62]:
array3 = np.array([np.arange(1,6), np.arange(10,15)]) # Criando um array de arrays
array3 # Exibindo o array

array([[ 1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14]])

In [63]:
array3.ndim # Verificando a dimensão do array

2

In [64]:
array3.ravel() # Transformando o array em um array 1D

array([ 1,  2,  3,  4,  5, 10, 11, 12, 13, 14])

In [65]:
array3.T.ravel() # Transformando o array transposto em um array 1D

array([ 1, 10,  2, 11,  3, 12,  4, 13,  5, 14])

## Operadores Lógicos

In [66]:
np.random.seed(100) # Definindo a semente para reprodução dos resultados
array4 = np.random.randint(1, 10, size = (4,4)) # Criando um array 2D com números aleatórios de 1 a 10
array4 # Exibindo o array

array([[9, 9, 4, 8],
       [8, 1, 5, 3],
       [6, 3, 3, 3],
       [2, 1, 9, 5]])

In [67]:
np.any((array4 % 7) == 0) # Verificando se algum elemento do array é divisível por 7

False

In [68]:
np.all(array4 < 11) # Verificando se todos os elementos do array são menores que 11

True

In [69]:
np.where(np.logical_and(array4[:,1]>2, array4[:,1]<9)) # Retornar o índice dos elementos que são maiores que 2 e menores que 9 na segunda coluna

(array([2], dtype=int64),)

In [70]:
np.intersect1d(np.where(array4[:,1]>2), np.where(array4[:,1]<9)) # Retornar o índice dos elementos que são maiores que 2 e menores que 9 na segunda coluna

array([2], dtype=int64)

In [71]:
array4[2] # Acessando o terceiro elemento do array

array([6, 3, 3, 3])

## Reshaping e Ordenação de Arrays

In [72]:
array5 = np.arange(1,16) # Criando um array de 1 a 15
array5 # Exibindo o array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [73]:
array5.reshape(3,5) # Redimensionando o array para 3 linhas e 5 colunas

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [74]:
array7 = np.array([[3,2],[10,-1]]) # Criando um array 2D
array7 # Exibindo o array

array([[ 3,  2],
       [10, -1]])

In [75]:
array7.sort(axis = 1) # Ordenando o array pelas linhas
array7 # Exibindo o array

array([[ 2,  3],
       [-1, 10]])

In [76]:
array8 = np.array([[3,2],[10,-1]]) # Criando um array 2D
array8 # Exibindo o array

array([[ 3,  2],
       [10, -1]])

In [77]:
array8.sort(axis = 0) # Ordenando o array pelas colunas
array8 # Exibindo o array

array([[ 3, -1],
       [10,  2]])