# Cápitulo 02 - Arquivo 04 - Estudo de Caso

In [71]:
# Importando bibliotecas e imprimir versão:
from platform import python_version
print('Versão Python:', python_version(), '\n')

import numpy as np
import warnings
warnings.filterwarnings("ignore") # Ignorar mensagens de aviso

%reload_ext watermark
%watermark -a "gustavogzr" --iversions

Versão Python: 3.11.1 

Author: gustavogzr

numpy: 1.25.2



In [72]:
np.set_printoptions(suppress=True, linewidth=200, precision=2) 
# Configuração de impressão dos arrays. Suprimir notação científica, aumentar largura de impressão e precisão de casas decimais

Para maiores detalhes sobre o np.set_printoptions, acesse o link: https://numpy.org/doc/stable/reference/generated/numpy.set_printoptions.html

## Carregando o Dataset

Para maiores detalhes, acessar o link: https://numpy.org/doc/stable/reference/generated/numpy.genfromtxt.html

In [73]:
dados = np.genfromtxt('.arquivos_DSA/dados/dataset1.csv',
                      delimiter=';',
                      skip_header=1,
                      autostrip=True,
                      encoding='cp1252')
# skip_header=1 pula a primeira linha do arquivo
# autostrip=True remove espaços em branco no início e no final dos dados

In [74]:
type(dados) # Tipo do objeto. ndarray = n-dimensional array

numpy.ndarray

In [75]:
dados.shape # Formato do array. 

(10000, 14)

In [76]:
dados.view() # Visualização dos dados

array([[48010226.  ,         nan,    35000.  , ...,         nan,         nan,     9452.96],
       [57693261.  ,         nan,    30000.  , ...,         nan,         nan,     4679.7 ],
       [59432726.  ,         nan,    15000.  , ...,         nan,         nan,     1969.83],
       ...,
       [50415990.  ,         nan,    10000.  , ...,         nan,         nan,     2185.64],
       [46154151.  ,         nan,         nan, ...,         nan,         nan,     3199.4 ],
       [66055249.  ,         nan,    10000.  , ...,         nan,         nan,      301.9 ]])

Várias colunas estão apresentando dados nan. O NumPy definiu erroneamente o tipo de dados das colunas e considerou colunas com strings como float. Iremos corrigir isso.

## Verificando valores ausentes

In [77]:
np.isnan(dados).sum() # Contagem de valores ausentes

88005

In [78]:
valor_coringa = np.nanmax(dados) + 1 # Valor coringa para substituir os valores ausentes. A função np.nanmax() retorna o maior valor do array ignorando os valores ausentes
print(valor_coringa)

68616520.0


In [79]:
media_ignorando_nan = np.nanmean(dados, axis=0) # Cálculo da média ignorando os valores ausentes. axis=0 indica que a média será calculada ao longo das colunas
print(media_ignorando_nan)

[54015809.19         nan    15273.46         nan    15311.04         nan       16.62      440.92         nan         nan         nan         nan         nan     3143.85]


In [80]:
colunas_string = np.argwhere(np.isnan(media_ignorando_nan)).squeeze() # Identificação das colunas que possuem valores ausentes
# argwhere() retorna os índices dos elementos que são True
# squeeze() converte para um array unidimensional
colunas_string # Visualização das colunas de string

array([ 1,  3,  5,  8,  9, 10, 11, 12], dtype=int64)

In [81]:
colunas_numericas = np.argwhere(np.isnan(media_ignorando_nan) == False).squeeze() # Identificação das colunas que não possuem valores ausentes
colunas_numericas # Visualização das colunas numéricas

array([ 0,  2,  4,  6,  7, 13], dtype=int64)

Agora iremos importar novamente o dataset, separando colunas do tipo string de colunas numéricas.

In [82]:
# Carregamento das colunas tipo string:
arr_strings = np.genfromtxt('.arquivos_DSA/dados/dataset1.csv',
                            delimiter=';',
                            skip_header=1,
                            autostrip=True,
                            usecols=colunas_string,
                            dtype=str,
                            encoding='cp1252')
# usecols=colunas_string indica que apenas as colunas identificadas como string serão carregadas
# dtype=str indica que os dados carregados serão do tipo string
arr_strings # Visualização dos dados

array([['May-15', 'Current', '36 months', ..., 'Verified', 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['', 'Current', '36 months', ..., 'Source Verified', 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['Sep-15', 'Current', '36 months', ..., 'Verified', 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ...,
       ['Jun-15', 'Current', '36 months', ..., 'Source Verified', 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
       ['Apr-15', 'Current', '36 months', ..., 'Source Verified', 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
       ['Dec-15', 'Current', '36 months', ..., '', 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL']], dtype='<U69')

In [83]:
# Carregamento das colunas tipo numérico:
arr_numericos = np.genfromtxt('.arquivos_DSA/dados/dataset1.csv',
                              delimiter=';',
                              skip_header=1,
                              autostrip=True,
                              usecols=colunas_numericas,
                              filling_values=valor_coringa,
                              encoding='cp1252')
# filling_values=valor_coringa substitui os valores ausentes pelo valor coringa
arr_numericos # Visualização dos dados

array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  , 68616520.  ,      938.57,     4679.7 ],
       [59432726.  ,    15000.  ,    15000.  , 68616520.  ,      494.86,     1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  , 68616520.  , 68616520.  ,     2185.64],
       [46154151.  , 68616520.  ,    10000.  ,       16.55,      354.3 ,     3199.4 ],
       [66055249.  ,    10000.  ,    10000.  , 68616520.  ,      309.97,      301.9 ]])

Agora iremos extrair os cabeçalhos das colunas.

In [84]:
arr_nome_colunas = np.genfromtxt('.arquivos_DSA/dados/dataset1.csv',
                                delimiter=';',
                                autostrip=True,
                                skip_footer=dados.shape[0],
                                dtype=str,
                                encoding='cp1252')
# skip_footer=dados.shape[0] pula o rodapé do arquivo
arr_nome_colunas # Visualização dos dados

array(['id', 'issue_d', 'loan_amnt', 'loan_status', 'funded_amnt', 'term', 'int_rate', 'installment', 'grade', 'sub_grade', 'verification_status', 'url', 'addr_state', 'total_pymnt'], dtype='<U19')

In [85]:
# Separar os cabeçalhos das colunas numéricas e de string:
header_strings = arr_nome_colunas[colunas_string] # Cabeçalhos das colunas de string
header_strings # Visualização dos dados

array(['issue_d', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url', 'addr_state'], dtype='<U19')

In [86]:
header_numeric = arr_nome_colunas[colunas_numericas] # Cabeçalhos das colunas numéricas
header_numeric # Visualização dos dados

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

## Função de CheckPoint

In [87]:
def checkpoint(file_name, checkpoint_header, checkpoint_data):
    np.savez(file_name, header=checkpoint_header, data=checkpoint_data) # Salvar os dados em um arquivo .npz
    checkpoint_variable = np.load(file_name + '.npz') # Carregar os dados do arquivo .npz
    return(checkpoint_variable) # Retornar os dados carregados

In [88]:
checkpoint_inicial = checkpoint(".arquivos_DSA/dados/Checkpoint-Inicial", header_strings, arr_strings) # Salvar os dados em um arquivo .npz

In [89]:
checkpoint_inicial['data'] # Visualização dos dados

array([['May-15', 'Current', '36 months', ..., 'Verified', 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['', 'Current', '36 months', ..., 'Source Verified', 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['Sep-15', 'Current', '36 months', ..., 'Verified', 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ...,
       ['Jun-15', 'Current', '36 months', ..., 'Source Verified', 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
       ['Apr-15', 'Current', '36 months', ..., 'Source Verified', 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
       ['Dec-15', 'Current', '36 months', ..., '', 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL']], dtype='<U69')

In [90]:
np.array_equal(checkpoint_inicial['data'], arr_strings) # Verificar se os dados são iguais

True

## Manipulando as colunas do tipo string

In [91]:
header_strings # Visualização dos dados

array(['issue_d', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url', 'addr_state'], dtype='<U19')

In [92]:
header_strings[0] = 'issue_date' # Alterar o nome da primeira coluna
header_strings # Visualização dos dados

array(['issue_date', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url', 'addr_state'], dtype='<U19')

In [93]:
arr_strings # Visualização dos dados

array([['May-15', 'Current', '36 months', ..., 'Verified', 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['', 'Current', '36 months', ..., 'Source Verified', 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['Sep-15', 'Current', '36 months', ..., 'Verified', 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ...,
       ['Jun-15', 'Current', '36 months', ..., 'Source Verified', 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
       ['Apr-15', 'Current', '36 months', ..., 'Source Verified', 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
       ['Dec-15', 'Current', '36 months', ..., '', 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL']], dtype='<U69')

## Pré-processamento da coluna issue_date com Label Encoding

In [94]:
np.unique(arr_strings[:, 0]) # Verificar os valores únicos da primeira coluna

array(['', 'Apr-15', 'Aug-15', 'Dec-15', 'Feb-15', 'Jan-15', 'Jul-15', 'Jun-15', 'Mar-15', 'May-15', 'Nov-15', 'Oct-15', 'Sep-15'], dtype='<U69')

In [95]:
arr_strings[:, 0] = np.chararray.strip(arr_strings[:, 0], "-15") # Remover espaços em branco
np.unique(arr_strings[:, 0]) # Verificar os valores únicos da primeira coluna

array(['', 'Apr', 'Aug', 'Dec', 'Feb', 'Jan', 'Jul', 'Jun', 'Mar', 'May', 'Nov', 'Oct', 'Sep'], dtype='<U69')

In [96]:
meses = np.array(['','Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec']) # Array com os meses do ano

In [97]:
for i in range(13): # Loop para substituir os meses pelo número correspondente
    arr_strings[:, 0] = np.where(arr_strings[:, 0] == meses[i], i, arr_strings[:, 0]) # Substituir os meses pelo número correspondente

np.unique(arr_strings[:, 0]) # Verificar os valores únicos da primeira coluna

array(['0', '1', '10', '11', '12', '2', '3', '4', '5', '6', '7', '8', '9'], dtype='<U69')

## Pré-processamento da coluna loan_status com Binarização

In [98]:
np.unique(arr_strings[:, 1]) # Verificar os valores únicos da segunda coluna

array(['', 'Charged Off', 'Current', 'Default', 'Fully Paid', 'In Grace Period', 'Issued', 'Late (16-30 days)', 'Late (31-120 days)'], dtype='<U69')

In [99]:
np.unique(arr_strings[:, 1]).size # Contar os valores únicos da segunda coluna

9

In [100]:
## Vamos converter os 9 dados categóricos em apenas 2 númericos
status_bad = np.array(['', 'Charged Off', 'Default', 'Late (31-120 days']) # Array com os status ruins
arr_strings[:, 1] = np.where(np.isin(arr_strings[:, 1], status_bad), 0, 1) # Substituir os status ruins por 0 e os demais por 1
np.unique(arr_strings[:, 1]) # Verificar os valores únicos da segunda coluna

array(['0', '1'], dtype='<U69')

## Pré-processamento da coluna term com limpeza de strings

In [101]:
np.unique(arr_strings[:, 2]) # Verificar os valores únicos da terceira coluna

array(['', '36 months', '60 months'], dtype='<U69')

In [102]:
arr_strings[:, 2] = np.chararray.strip(arr_strings[:, 2], " months") # Remover a palavra "months"
np.unique(arr_strings[:, 2]) # Verificar os valores únicos da terceira coluna

array(['', '36', '60'], dtype='<U69')

In [103]:
header_strings[2] = 'term_months' # Alterar o nome da terceira coluna

In [104]:
arr_strings[:, 2] = np.where(arr_strings[:, 2] == '', '60', arr_strings[:, 2]) # Substituir os valores ausentes por 0

In [105]:
np.unique(arr_strings[:, 2]) # Verificar os valores únicos da terceira coluna

array(['36', '60'], dtype='<U69')

## Pré-processamento das colunas grade e sub_grade com a Frequência

In [106]:
np.unique(arr_strings[:, 3]) # Verificar os valores únicos da quarta coluna

array(['', 'A', 'B', 'C', 'D', 'E', 'F', 'G'], dtype='<U69')

In [107]:
np.unique(arr_strings[:, 4]) # Verificar os valores únicos da quarta coluna

array(['', 'A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4', 'C5', 'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4', 'F5', 'G1',
       'G2', 'G3', 'G4', 'G5'], dtype='<U69')

In [108]:
np.unique(arr_strings[:, 3])[1:] # remover o primeiro elemento da lista (valor ausente) de valores únicos

array(['A', 'B', 'C', 'D', 'E', 'F', 'G'], dtype='<U69')

In [109]:
for i in np.unique(arr_strings[:, 3])[1:]:
    arr_strings[:, 4] = np.where((arr_strings[:,4]=='') & (arr_strings[:,3]==i), i + '5', arr_strings[:,4]) # Substituir os valores ausentes pelo valor correspondente

np.unique(arr_strings[:, 4], return_counts=True) # Verificar os valores únicos da quarta coluna

(array(['', 'A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4', 'C5', 'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4', 'F5', 'G1',
        'G2', 'G3', 'G4', 'G5'], dtype='<U69'),
 array([  9, 285, 278, 239, 323, 592, 509, 517, 530, 553, 633, 629, 567, 586, 564, 577, 391, 267, 250, 255, 288, 235, 162, 171, 139, 160,  94,  52,  34,  43,  24,  19,  10,   3,   7,   5], dtype=int64))

In [110]:
arr_strings[:, 4] = np.where(arr_strings[:, 4] == '', 'H1', arr_strings[:, 4]) # Substituir os valores ausentes por H1
np.unique(arr_strings[:, 4]) # Verificar os valores únicos da quarta coluna

array(['A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4', 'C5', 'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4', 'F5', 'G1', 'G2',
       'G3', 'G4', 'G5', 'H1'], dtype='<U69')

Vamos remover a variável grade do modelo, pois a variável sub_grade já é suficiente para representar a mesma informação.

In [111]:
arr_strings = np.delete(arr_strings, 3, axis=1) # Excluir a quarta coluna
arr_strings[:,1:4] # Visualização dos dados

array([['1', '36', 'C3'],
       ['1', '36', 'A5'],
       ['1', '36', 'B5'],
       ...,
       ['1', '36', 'A5'],
       ['1', '36', 'D2'],
       ['1', '36', 'A4']], dtype='<U69')

In [112]:
header_strings = np.delete(header_strings, 3) # Excluir o nome da quarta coluna
header_strings # Visualização dos dados

array(['issue_date', 'loan_status', 'term_months', 'sub_grade', 'verification_status', 'url', 'addr_state'], dtype='<U19')

In [113]:
np.unique(arr_strings[:, 3]) # Verificar os valores únicos da quarta coluna

array(['A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4', 'C5', 'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4', 'F5', 'G1', 'G2',
       'G3', 'G4', 'G5', 'H1'], dtype='<U69')

In [114]:
keys = list(np.unique(arr_strings[:, 3])) # cria uma lista com os valores únicos da quarta coluna
keys[0] # Visualização dos dados

'A1'

In [115]:
values = list(range(1, np.unique(arr_strings[:, 3]).shape[0] + 1)) # Cria uma lista com os valores de 1 a n, onde n é o número de valores únicos da quarta coluna
values[0] # Visualização dos dados

1

In [116]:
dict_sub_grade = dict(zip(keys, values)) # Cria um dicionário com as chaves e valores correspondentes
# zip() combina as chaves e valores em um dicionário
dict_sub_grade # Visualização dos dados

{'A1': 1,
 'A2': 2,
 'A3': 3,
 'A4': 4,
 'A5': 5,
 'B1': 6,
 'B2': 7,
 'B3': 8,
 'B4': 9,
 'B5': 10,
 'C1': 11,
 'C2': 12,
 'C3': 13,
 'C4': 14,
 'C5': 15,
 'D1': 16,
 'D2': 17,
 'D3': 18,
 'D4': 19,
 'D5': 20,
 'E1': 21,
 'E2': 22,
 'E3': 23,
 'E4': 24,
 'E5': 25,
 'F1': 26,
 'F2': 27,
 'F3': 28,
 'F4': 29,
 'F5': 30,
 'G1': 31,
 'G2': 32,
 'G3': 33,
 'G4': 34,
 'G5': 35,
 'H1': 36}

In [117]:
for i in np.unique(arr_strings[:,3]):
    arr_strings[:, 3] = np.where(arr_strings[:, 3] == i, dict_sub_grade[i], arr_strings[:, 3]) # Substituir os valores pelos valores numéricos correspondentes

np.unique(arr_strings[:, 3]) # Verificar os valores únicos da quarta coluna

array(['1', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '2', '20', '21', '22', '23', '24', '25', '26', '27', '28', '29', '3', '30', '31', '32', '33', '34', '35', '36', '4', '5', '6',
       '7', '8', '9'], dtype='<U69')

## Pré-processamento da coluna verification_status com Binarização

In [118]:
np.unique(arr_strings[:, 4]) # Verificar os valores únicos da quinta coluna

array(['', 'Not Verified', 'Source Verified', 'Verified'], dtype='<U69')

In [119]:
arr_strings[:, 4] = np.where((arr_strings[:, 4] == '') | (arr_strings[:, 4] == 'Not Verified'), '0', 1) # Substituir os valores ausentes e 'Not Verified' por 0 e os demais por 1
np.unique(arr_strings[:, 4]) # Verificar os valores únicos da quinta coluna

array(['0', '1'], dtype='<U69')

## Pré-processamento da coluna url com extração de ID

In [120]:
arr_strings[:, 5]

array(['https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', ..., 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249'], dtype='<U69')

In [121]:
np.chararray.strip(arr_strings[:, 5], "https://www.lendingclub.com/browse/loanDetail.action?loan_id=") # Remover a URL

chararray(['48010226', '57693261', '59432726', ..., '50415990', '46154151', '66055249'], dtype='<U69')

In [122]:
arr_strings[:, 5] = np.chararray.strip(arr_strings[:, 5], "https://www.lendingclub.com/browse/loanDetail.action?loan_id=") # Remover a URL
arr_strings[:, 5] # Visualização dos dados

array(['48010226', '57693261', '59432726', ..., '50415990', '46154151', '66055249'], dtype='<U69')

In [123]:
arr_strings[:, 5].astype(dtype=np.int32) # Converter a coluna para o tipo inteiro

array([48010226, 57693261, 59432726, ..., 50415990, 46154151, 66055249])

In [124]:
# Aparentemente a coluna id também está presente no array numérico. Vamos verificar:
arr_numericos[:, 0].astype(dtype=np.int32) # Converter a coluna para o tipo inteiro

array([48010226, 57693261, 59432726, ..., 50415990, 46154151, 66055249])

In [125]:
# Realizar comparação entre as colunas id dos arrays arr_strings e arr_numericos
np.array_equal(arr_numericos[:, 0].astype(dtype=np.int32), arr_strings[:, 5].astype(dtype=np.int32))

True

Como as colunas são idênticas, vamos remover a variável url do modelo.

In [126]:
arr_strings = np.delete(arr_strings, 5, axis=1) # Excluir a sexta coluna
arr_strings # Visualização dos dados

array([['5', '1', '36', '13', '1', 'CA'],
       ['0', '1', '36', '5', '1', 'NY'],
       ['9', '1', '36', '10', '1', 'PA'],
       ...,
       ['6', '1', '36', '5', '1', 'CA'],
       ['4', '1', '36', '17', '1', 'OH'],
       ['12', '1', '36', '4', '0', 'IL']], dtype='<U69')

In [127]:
header_strings = np.delete(header_strings, 5) # Excluir o nome da sexta coluna
header_strings # Visualização dos dados

array(['issue_date', 'loan_status', 'term_months', 'sub_grade', 'verification_status', 'addr_state'], dtype='<U19')

## Pré-processamento da coluna addr_state com Categorização

In [128]:
header_strings[5] = 'state_address' # Alterar o nome da sexta coluna

In [129]:
states_names, states_count = np.unique(arr_strings[:, 5], return_counts=True) # Contar os valores únicos da sexta coluna

In [130]:
states_count_sorted = np.argsort(-states_count) # Ordenar os estados em ordem decrescente

In [131]:
states_names[states_count_sorted], states_count[states_count_sorted] # Visualização dos dados

(array(['CA', 'NY', 'TX', 'FL', '', 'IL', 'NJ', 'GA', 'PA', 'OH', 'MI', 'NC', 'VA', 'MD', 'AZ', 'WA', 'MA', 'CO', 'MO', 'MN', 'IN', 'WI', 'CT', 'TN', 'NV', 'AL', 'LA', 'OR', 'SC', 'KY', 'KS', 'OK',
        'UT', 'AR', 'MS', 'NH', 'NM', 'WV', 'HI', 'RI', 'MT', 'DE', 'DC', 'WY', 'AK', 'NE', 'SD', 'VT', 'ND', 'ME'], dtype='<U69'),
 array([1336,  777,  758,  690,  500,  389,  341,  321,  320,  312,  267,  261,  242,  222,  220,  216,  210,  201,  160,  156,  152,  148,  143,  143,  130,  119,  116,  108,  107,   84,   84,   83,
          74,   74,   61,   58,   57,   49,   44,   40,   28,   27,   27,   27,   26,   25,   24,   17,   16,   10], dtype=int64))

In [132]:
arr_strings[:, 5] = np.where(arr_strings[:, 5] == '', 0, arr_strings[:, 5]) # Substituir os valores ausentes por 0

In [133]:
# Iremos separar os estados em regiões
states_west = np.array(['WA', 'OR', 'CA', 'NV', 'ID', 'MT', 'WY', 'UT', 'CO', 'AZ', 'NM', 'HI', 'AK']) # Estados da região oeste
states_south = np.array(['TX', 'OK', 'AR', 'LA', 'MS', 'AL', 'TN', 'KY', 'FL', 'GA', 'SC', 'NC', 'VA', 'WV', 'MD', 'DE', 'DC']) # Estados da região sul
states_midwest = np.array(['ND', 'SD', 'NE', 'KS', 'MN', 'IA', 'MO', 'WI', 'IL', 'IN', 'MI', 'OH']) # Estados da região centro-oeste
states_east = np.array(['PA', 'NY', 'NJ', 'CT', 'MA', 'VT', 'NH', 'ME', 'RI']) # Estados da região leste

In [134]:
# Agora iremos substituir cada estado pelo ID da sua região
arr_strings[:,5] = np.where(np.isin(arr_strings[:,5], states_west), 1, arr_strings[:,5]) # Região oeste
arr_strings[:,5] = np.where(np.isin(arr_strings[:,5], states_south), 2, arr_strings[:,5]) # Região sul
arr_strings[:,5] = np.where(np.isin(arr_strings[:,5], states_midwest), 3, arr_strings[:,5]) # Região centro-oeste
arr_strings[:,5] = np.where(np.isin(arr_strings[:,5], states_east), 4, arr_strings[:,5]) # Região leste

In [135]:
np.unique(arr_strings[:, 5]) # Verificar os valores únicos da sexta coluna

array(['0', '1', '2', '3', '4'], dtype='<U69')

## Convertendo o Array de Strings para Numérico

In [136]:
arr_strings # Visualização dos dados

array([['5', '1', '36', '13', '1', '1'],
       ['0', '1', '36', '5', '1', '4'],
       ['9', '1', '36', '10', '1', '4'],
       ...,
       ['6', '1', '36', '5', '1', '1'],
       ['4', '1', '36', '17', '1', '3'],
       ['12', '1', '36', '4', '0', '3']], dtype='<U69')

In [137]:
arr_strings = arr_strings.astype(int) # Converter os dados para o tipo inteiro
arr_strings # Visualização dos dados

array([[ 5,  1, 36, 13,  1,  1],
       [ 0,  1, 36,  5,  1,  4],
       [ 9,  1, 36, 10,  1,  4],
       ...,
       [ 6,  1, 36,  5,  1,  1],
       [ 4,  1, 36, 17,  1,  3],
       [12,  1, 36,  4,  0,  3]])

In [138]:
arr_strings.dtype # Tipo dos dados

dtype('int32')

## CheckPoint com Variáveis do Tipo String Limpas e Pré-Processadas

In [139]:
checkpoint_strings = checkpoint(".arquivos_DSA/dados/Checkpoint-Strings", header_strings, arr_strings) # Salvar os dados em um arquivo .npz

In [140]:
checkpoint_strings['header']

array(['issue_date', 'loan_status', 'term_months', 'sub_grade', 'verification_status', 'state_address'], dtype='<U19')

In [141]:
checkpoint_strings['data']

array([[ 5,  1, 36, 13,  1,  1],
       [ 0,  1, 36,  5,  1,  4],
       [ 9,  1, 36, 10,  1,  4],
       ...,
       [ 6,  1, 36,  5,  1,  1],
       [ 4,  1, 36, 17,  1,  3],
       [12,  1, 36,  4,  0,  3]])

In [142]:
np.array_equal(checkpoint_strings['data'], arr_strings)	

True

## Manipulando as colunas Numéricas