# Cápitulo 02 - Arquivo 04 - Estudo de Caso

In [671]:
# Importando bibliotecas e imprimir versão:
from platform import python_version
print('Versão Python:', python_version(), '\n')

import numpy as np
import warnings
warnings.filterwarnings("ignore") # Ignorar mensagens de aviso

%reload_ext watermark
%watermark -a "gustavogzr" --iversions

Versão Python: 3.11.1 

Author: gustavogzr

numpy: 1.25.2



In [672]:
np.set_printoptions(suppress=True, linewidth=200, precision=2) 
# Configuração de impressão dos arrays. Suprimir notação científica, aumentar largura de impressão e precisão de casas decimais

Para maiores detalhes sobre o np.set_printoptions, acesse o link: https://numpy.org/doc/stable/reference/generated/numpy.set_printoptions.html

## Carregando o Dataset

Para maiores detalhes, acessar o link: https://numpy.org/doc/stable/reference/generated/numpy.genfromtxt.html

In [673]:
dados = np.genfromtxt('.arquivos_DSA/dados/dataset1.csv',
                      delimiter=';',
                      skip_header=1,
                      autostrip=True,
                      encoding='cp1252')
# skip_header=1 pula a primeira linha do arquivo
# autostrip=True remove espaços em branco no início e no final dos dados

In [674]:
type(dados) # Tipo do objeto. ndarray = n-dimensional array

numpy.ndarray

In [675]:
dados.shape # Formato do array. 

(10000, 14)

In [676]:
dados.view() # Visualização dos dados

array([[48010226.  ,         nan,    35000.  , ...,         nan,         nan,     9452.96],
       [57693261.  ,         nan,    30000.  , ...,         nan,         nan,     4679.7 ],
       [59432726.  ,         nan,    15000.  , ...,         nan,         nan,     1969.83],
       ...,
       [50415990.  ,         nan,    10000.  , ...,         nan,         nan,     2185.64],
       [46154151.  ,         nan,         nan, ...,         nan,         nan,     3199.4 ],
       [66055249.  ,         nan,    10000.  , ...,         nan,         nan,      301.9 ]])

Várias colunas estão apresentando dados nan. O NumPy definiu erroneamente o tipo de dados das colunas e considerou colunas com strings como float. Iremos corrigir isso.

## Verificando valores ausentes

In [677]:
np.isnan(dados).sum() # Contagem de valores ausentes

88005

In [678]:
valor_coringa = np.nanmax(dados) + 1 # Valor coringa para substituir os valores ausentes. A função np.nanmax() retorna o maior valor do array ignorando os valores ausentes
print(valor_coringa)

68616520.0


In [679]:
media_ignorando_nan = np.nanmean(dados, axis=0) # Cálculo da média ignorando os valores ausentes. axis=0 indica que a média será calculada ao longo das colunas
print(media_ignorando_nan)

[54015809.19         nan    15273.46         nan    15311.04         nan       16.62      440.92         nan         nan         nan         nan         nan     3143.85]


In [680]:
colunas_string = np.argwhere(np.isnan(media_ignorando_nan)).squeeze() # Identificação das colunas que possuem valores ausentes
# argwhere() retorna os índices dos elementos que são True
# squeeze() converte para um array unidimensional
colunas_string # Visualização das colunas de string

array([ 1,  3,  5,  8,  9, 10, 11, 12], dtype=int64)

In [681]:
colunas_numericas = np.argwhere(np.isnan(media_ignorando_nan) == False).squeeze() # Identificação das colunas que não possuem valores ausentes
colunas_numericas # Visualização das colunas numéricas

array([ 0,  2,  4,  6,  7, 13], dtype=int64)

Agora iremos importar novamente o dataset, separando colunas do tipo string de colunas numéricas.

In [682]:
# Carregamento das colunas tipo string:
arr_strings = np.genfromtxt('.arquivos_DSA/dados/dataset1.csv',
                            delimiter=';',
                            skip_header=1,
                            autostrip=True,
                            usecols=colunas_string,
                            dtype=str,
                            encoding='cp1252')
# usecols=colunas_string indica que apenas as colunas identificadas como string serão carregadas
# dtype=str indica que os dados carregados serão do tipo string
arr_strings # Visualização dos dados

array([['May-15', 'Current', '36 months', ..., 'Verified', 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['', 'Current', '36 months', ..., 'Source Verified', 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['Sep-15', 'Current', '36 months', ..., 'Verified', 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ...,
       ['Jun-15', 'Current', '36 months', ..., 'Source Verified', 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
       ['Apr-15', 'Current', '36 months', ..., 'Source Verified', 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
       ['Dec-15', 'Current', '36 months', ..., '', 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL']], dtype='<U69')

In [683]:
# Carregamento das colunas tipo numérico:
arr_numericos = np.genfromtxt('.arquivos_DSA/dados/dataset1.csv',
                              delimiter=';',
                              skip_header=1,
                              autostrip=True,
                              usecols=colunas_numericas,
                              filling_values=valor_coringa,
                              encoding='cp1252')
# filling_values=valor_coringa substitui os valores ausentes pelo valor coringa
arr_numericos # Visualização dos dados

array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  , 68616520.  ,      938.57,     4679.7 ],
       [59432726.  ,    15000.  ,    15000.  , 68616520.  ,      494.86,     1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  , 68616520.  , 68616520.  ,     2185.64],
       [46154151.  , 68616520.  ,    10000.  ,       16.55,      354.3 ,     3199.4 ],
       [66055249.  ,    10000.  ,    10000.  , 68616520.  ,      309.97,      301.9 ]])

Agora iremos extrair os cabeçalhos das colunas.

In [684]:
arr_nome_colunas = np.genfromtxt('.arquivos_DSA/dados/dataset1.csv',
                                delimiter=';',
                                autostrip=True,
                                skip_footer=dados.shape[0],
                                dtype=str,
                                encoding='cp1252')
# skip_footer=dados.shape[0] pula o rodapé do arquivo
arr_nome_colunas # Visualização dos dados

array(['id', 'issue_d', 'loan_amnt', 'loan_status', 'funded_amnt', 'term', 'int_rate', 'installment', 'grade', 'sub_grade', 'verification_status', 'url', 'addr_state', 'total_pymnt'], dtype='<U19')

In [685]:
# Separar os cabeçalhos das colunas numéricas e de string:
header_strings = arr_nome_colunas[colunas_string] # Cabeçalhos das colunas de string
header_strings # Visualização dos dados

array(['issue_d', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url', 'addr_state'], dtype='<U19')

In [686]:
header_numeric = arr_nome_colunas[colunas_numericas] # Cabeçalhos das colunas numéricas
header_numeric # Visualização dos dados

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

## Função de CheckPoint

In [687]:
def checkpoint(file_name, checkpoint_header, checkpoint_data):
    np.savez(file_name, header=checkpoint_header, data=checkpoint_data) # Salvar os dados em um arquivo .npz
    checkpoint_variable = np.load(file_name + '.npz') # Carregar os dados do arquivo .npz
    return(checkpoint_variable) # Retornar os dados carregados

In [688]:
checkpoint_inicial = checkpoint(".arquivos_DSA/dados/Checkpoint-Inicial", header_strings, arr_strings) # Salvar os dados em um arquivo .npz

In [689]:
checkpoint_inicial['data'] # Visualização dos dados

array([['May-15', 'Current', '36 months', ..., 'Verified', 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['', 'Current', '36 months', ..., 'Source Verified', 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['Sep-15', 'Current', '36 months', ..., 'Verified', 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ...,
       ['Jun-15', 'Current', '36 months', ..., 'Source Verified', 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
       ['Apr-15', 'Current', '36 months', ..., 'Source Verified', 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
       ['Dec-15', 'Current', '36 months', ..., '', 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL']], dtype='<U69')

In [690]:
np.array_equal(checkpoint_inicial['data'], arr_strings) # Verificar se os dados são iguais

True

## Manipulando as colunas do tipo string

In [691]:
header_strings # Visualização dos dados

array(['issue_d', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url', 'addr_state'], dtype='<U19')

In [692]:
header_strings[0] = 'issue_date' # Alterar o nome da primeira coluna
header_strings # Visualização dos dados

array(['issue_date', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url', 'addr_state'], dtype='<U19')

In [693]:
arr_strings # Visualização dos dados

array([['May-15', 'Current', '36 months', ..., 'Verified', 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['', 'Current', '36 months', ..., 'Source Verified', 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['Sep-15', 'Current', '36 months', ..., 'Verified', 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ...,
       ['Jun-15', 'Current', '36 months', ..., 'Source Verified', 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
       ['Apr-15', 'Current', '36 months', ..., 'Source Verified', 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
       ['Dec-15', 'Current', '36 months', ..., '', 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL']], dtype='<U69')

## Pré-processamento da coluna issue_date com Label Encoding

In [694]:
np.unique(arr_strings[:, 0]) # Verificar os valores únicos da primeira coluna

array(['', 'Apr-15', 'Aug-15', 'Dec-15', 'Feb-15', 'Jan-15', 'Jul-15', 'Jun-15', 'Mar-15', 'May-15', 'Nov-15', 'Oct-15', 'Sep-15'], dtype='<U69')

In [695]:
arr_strings[:, 0] = np.chararray.strip(arr_strings[:, 0], "-15") # Remover espaços em branco
np.unique(arr_strings[:, 0]) # Verificar os valores únicos da primeira coluna

array(['', 'Apr', 'Aug', 'Dec', 'Feb', 'Jan', 'Jul', 'Jun', 'Mar', 'May', 'Nov', 'Oct', 'Sep'], dtype='<U69')

In [696]:
meses = np.array(['','Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec']) # Array com os meses do ano

In [697]:
for i in range(13): # Loop para substituir os meses pelo número correspondente
    arr_strings[:, 0] = np.where(arr_strings[:, 0] == meses[i], i, arr_strings[:, 0]) # Substituir os meses pelo número correspondente

np.unique(arr_strings[:, 0]) # Verificar os valores únicos da primeira coluna

array(['0', '1', '10', '11', '12', '2', '3', '4', '5', '6', '7', '8', '9'], dtype='<U69')

## Pré-processamento da coluna loan_status com Binarização

In [698]:
np.unique(arr_strings[:, 1]) # Verificar os valores únicos da segunda coluna

array(['', 'Charged Off', 'Current', 'Default', 'Fully Paid', 'In Grace Period', 'Issued', 'Late (16-30 days)', 'Late (31-120 days)'], dtype='<U69')

In [699]:
np.unique(arr_strings[:, 1]).size # Contar os valores únicos da segunda coluna

9

In [700]:
## Vamos converter os 9 dados categóricos em apenas 2 númericos
status_bad = np.array(['', 'Charged Off', 'Default', 'Late (31-120 days']) # Array com os status ruins
arr_strings[:, 1] = np.where(np.isin(arr_strings[:, 1], status_bad), 0, 1) # Substituir os status ruins por 0 e os demais por 1
np.unique(arr_strings[:, 1]) # Verificar os valores únicos da segunda coluna

array(['0', '1'], dtype='<U69')

## Pré-processamento da coluna term com limpeza de strings

In [701]:
np.unique(arr_strings[:, 2]) # Verificar os valores únicos da terceira coluna

array(['', '36 months', '60 months'], dtype='<U69')

In [702]:
arr_strings[:, 2] = np.chararray.strip(arr_strings[:, 2], " months") # Remover a palavra "months"
np.unique(arr_strings[:, 2]) # Verificar os valores únicos da terceira coluna

array(['', '36', '60'], dtype='<U69')

In [703]:
header_strings[2] = 'term_months' # Alterar o nome da terceira coluna

In [704]:
arr_strings[:, 2] = np.where(arr_strings[:, 2] == '', '60', arr_strings[:, 2]) # Substituir os valores ausentes por 0

In [705]:
np.unique(arr_strings[:, 2]) # Verificar os valores únicos da terceira coluna

array(['36', '60'], dtype='<U69')

## Pré-processamento das colunas grade e sub_grade com a Frequência

In [706]:
np.unique(arr_strings[:, 3]) # Verificar os valores únicos da quarta coluna

array(['', 'A', 'B', 'C', 'D', 'E', 'F', 'G'], dtype='<U69')

In [707]:
np.unique(arr_strings[:, 4]) # Verificar os valores únicos da quarta coluna

array(['', 'A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4', 'C5', 'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4', 'F5', 'G1',
       'G2', 'G3', 'G4', 'G5'], dtype='<U69')

In [708]:
np.unique(arr_strings[:, 3])[1:] # remover o primeiro elemento da lista (valor ausente) de valores únicos

array(['A', 'B', 'C', 'D', 'E', 'F', 'G'], dtype='<U69')

In [709]:
for i in np.unique(arr_strings[:, 3])[1:]:
    arr_strings[:, 4] = np.where((arr_strings[:,4]=='') & (arr_strings[:,3]==i), i + '5', arr_strings[:,4]) # Substituir os valores ausentes pelo valor correspondente

np.unique(arr_strings[:, 4], return_counts=True) # Verificar os valores únicos da quarta coluna

(array(['', 'A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4', 'C5', 'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4', 'F5', 'G1',
        'G2', 'G3', 'G4', 'G5'], dtype='<U69'),
 array([  9, 285, 278, 239, 323, 592, 509, 517, 530, 553, 633, 629, 567, 586, 564, 577, 391, 267, 250, 255, 288, 235, 162, 171, 139, 160,  94,  52,  34,  43,  24,  19,  10,   3,   7,   5], dtype=int64))

In [710]:
arr_strings[:, 4] = np.where(arr_strings[:, 4] == '', 'H1', arr_strings[:, 4]) # Substituir os valores ausentes por H1
np.unique(arr_strings[:, 4]) # Verificar os valores únicos da quarta coluna

array(['A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4', 'C5', 'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4', 'F5', 'G1', 'G2',
       'G3', 'G4', 'G5', 'H1'], dtype='<U69')

Vamos remover a variável grade do modelo, pois a variável sub_grade já é suficiente para representar a mesma informação.

In [711]:
arr_strings = np.delete(arr_strings, 3, axis=1) # Excluir a quarta coluna
arr_strings[:,1:4] # Visualização dos dados

array([['1', '36', 'C3'],
       ['1', '36', 'A5'],
       ['1', '36', 'B5'],
       ...,
       ['1', '36', 'A5'],
       ['1', '36', 'D2'],
       ['1', '36', 'A4']], dtype='<U69')

In [712]:
header_strings = np.delete(header_strings, 3) # Excluir o nome da quarta coluna
header_strings # Visualização dos dados

array(['issue_date', 'loan_status', 'term_months', 'sub_grade', 'verification_status', 'url', 'addr_state'], dtype='<U19')

In [713]:
np.unique(arr_strings[:, 3]) # Verificar os valores únicos da quarta coluna

array(['A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4', 'C5', 'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4', 'F5', 'G1', 'G2',
       'G3', 'G4', 'G5', 'H1'], dtype='<U69')

In [714]:
keys = list(np.unique(arr_strings[:, 3])) # cria uma lista com os valores únicos da quarta coluna
keys[0] # Visualização dos dados

'A1'

In [715]:
values = list(range(1, np.unique(arr_strings[:, 3]).shape[0] + 1)) # Cria uma lista com os valores de 1 a n, onde n é o número de valores únicos da quarta coluna
values[0] # Visualização dos dados

1

In [716]:
dict_sub_grade = dict(zip(keys, values)) # Cria um dicionário com as chaves e valores correspondentes
# zip() combina as chaves e valores em um dicionário
dict_sub_grade # Visualização dos dados

{'A1': 1,
 'A2': 2,
 'A3': 3,
 'A4': 4,
 'A5': 5,
 'B1': 6,
 'B2': 7,
 'B3': 8,
 'B4': 9,
 'B5': 10,
 'C1': 11,
 'C2': 12,
 'C3': 13,
 'C4': 14,
 'C5': 15,
 'D1': 16,
 'D2': 17,
 'D3': 18,
 'D4': 19,
 'D5': 20,
 'E1': 21,
 'E2': 22,
 'E3': 23,
 'E4': 24,
 'E5': 25,
 'F1': 26,
 'F2': 27,
 'F3': 28,
 'F4': 29,
 'F5': 30,
 'G1': 31,
 'G2': 32,
 'G3': 33,
 'G4': 34,
 'G5': 35,
 'H1': 36}

In [717]:
for i in np.unique(arr_strings[:,3]):
    arr_strings[:, 3] = np.where(arr_strings[:, 3] == i, dict_sub_grade[i], arr_strings[:, 3]) # Substituir os valores pelos valores numéricos correspondentes

np.unique(arr_strings[:, 3]) # Verificar os valores únicos da quarta coluna

array(['1', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '2', '20', '21', '22', '23', '24', '25', '26', '27', '28', '29', '3', '30', '31', '32', '33', '34', '35', '36', '4', '5', '6',
       '7', '8', '9'], dtype='<U69')

## Pré-processamento da coluna verification_status com Binarização

In [718]:
np.unique(arr_strings[:, 4]) # Verificar os valores únicos da quinta coluna

array(['', 'Not Verified', 'Source Verified', 'Verified'], dtype='<U69')

In [719]:
arr_strings[:, 4] = np.where((arr_strings[:, 4] == '') | (arr_strings[:, 4] == 'Not Verified'), '0', 1) # Substituir os valores ausentes e 'Not Verified' por 0 e os demais por 1
np.unique(arr_strings[:, 4]) # Verificar os valores únicos da quinta coluna

array(['0', '1'], dtype='<U69')

## Pré-processamento da coluna url com extração de ID

In [720]:
arr_strings[:, 5]

array(['https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', ..., 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249'], dtype='<U69')

In [721]:
np.chararray.strip(arr_strings[:, 5], "https://www.lendingclub.com/browse/loanDetail.action?loan_id=") # Remover a URL

chararray(['48010226', '57693261', '59432726', ..., '50415990', '46154151', '66055249'], dtype='<U69')

In [722]:
arr_strings[:, 5] = np.chararray.strip(arr_strings[:, 5], "https://www.lendingclub.com/browse/loanDetail.action?loan_id=") # Remover a URL
arr_strings[:, 5] # Visualização dos dados

array(['48010226', '57693261', '59432726', ..., '50415990', '46154151', '66055249'], dtype='<U69')

In [723]:
arr_strings[:, 5].astype(dtype=np.int32) # Converter a coluna para o tipo inteiro

array([48010226, 57693261, 59432726, ..., 50415990, 46154151, 66055249])

In [724]:
# Aparentemente a coluna id também está presente no array numérico. Vamos verificar:
arr_numericos[:, 0].astype(dtype=np.int32) # Converter a coluna para o tipo inteiro

array([48010226, 57693261, 59432726, ..., 50415990, 46154151, 66055249])

In [725]:
# Realizar comparação entre as colunas id dos arrays arr_strings e arr_numericos
np.array_equal(arr_numericos[:, 0].astype(dtype=np.int32), arr_strings[:, 5].astype(dtype=np.int32))

True

Como as colunas são idênticas, vamos remover a variável url do modelo.

In [726]:
arr_strings = np.delete(arr_strings, 5, axis=1) # Excluir a sexta coluna
arr_strings # Visualização dos dados

array([['5', '1', '36', '13', '1', 'CA'],
       ['0', '1', '36', '5', '1', 'NY'],
       ['9', '1', '36', '10', '1', 'PA'],
       ...,
       ['6', '1', '36', '5', '1', 'CA'],
       ['4', '1', '36', '17', '1', 'OH'],
       ['12', '1', '36', '4', '0', 'IL']], dtype='<U69')

In [727]:
header_strings = np.delete(header_strings, 5) # Excluir o nome da sexta coluna
header_strings # Visualização dos dados

array(['issue_date', 'loan_status', 'term_months', 'sub_grade', 'verification_status', 'addr_state'], dtype='<U19')

## Pré-processamento da coluna addr_state com Categorização

In [728]:
header_strings[5] = 'state_address' # Alterar o nome da sexta coluna

In [729]:
states_names, states_count = np.unique(arr_strings[:, 5], return_counts=True) # Contar os valores únicos da sexta coluna

In [730]:
states_count_sorted = np.argsort(-states_count) # Ordenar os estados em ordem decrescente

In [731]:
states_names[states_count_sorted], states_count[states_count_sorted] # Visualização dos dados

(array(['CA', 'NY', 'TX', 'FL', '', 'IL', 'NJ', 'GA', 'PA', 'OH', 'MI', 'NC', 'VA', 'MD', 'AZ', 'WA', 'MA', 'CO', 'MO', 'MN', 'IN', 'WI', 'CT', 'TN', 'NV', 'AL', 'LA', 'OR', 'SC', 'KY', 'KS', 'OK',
        'UT', 'AR', 'MS', 'NH', 'NM', 'WV', 'HI', 'RI', 'MT', 'DE', 'DC', 'WY', 'AK', 'NE', 'SD', 'VT', 'ND', 'ME'], dtype='<U69'),
 array([1336,  777,  758,  690,  500,  389,  341,  321,  320,  312,  267,  261,  242,  222,  220,  216,  210,  201,  160,  156,  152,  148,  143,  143,  130,  119,  116,  108,  107,   84,   84,   83,
          74,   74,   61,   58,   57,   49,   44,   40,   28,   27,   27,   27,   26,   25,   24,   17,   16,   10], dtype=int64))

In [732]:
arr_strings[:, 5] = np.where(arr_strings[:, 5] == '', 0, arr_strings[:, 5]) # Substituir os valores ausentes por 0

In [733]:
# Iremos separar os estados em regiões
states_west = np.array(['WA', 'OR', 'CA', 'NV', 'ID', 'MT', 'WY', 'UT', 'CO', 'AZ', 'NM', 'HI', 'AK']) # Estados da região oeste
states_south = np.array(['TX', 'OK', 'AR', 'LA', 'MS', 'AL', 'TN', 'KY', 'FL', 'GA', 'SC', 'NC', 'VA', 'WV', 'MD', 'DE', 'DC']) # Estados da região sul
states_midwest = np.array(['ND', 'SD', 'NE', 'KS', 'MN', 'IA', 'MO', 'WI', 'IL', 'IN', 'MI', 'OH']) # Estados da região centro-oeste
states_east = np.array(['PA', 'NY', 'NJ', 'CT', 'MA', 'VT', 'NH', 'ME', 'RI']) # Estados da região leste

In [734]:
# Agora iremos substituir cada estado pelo ID da sua região
arr_strings[:,5] = np.where(np.isin(arr_strings[:,5], states_west), 1, arr_strings[:,5]) # Região oeste
arr_strings[:,5] = np.where(np.isin(arr_strings[:,5], states_south), 2, arr_strings[:,5]) # Região sul
arr_strings[:,5] = np.where(np.isin(arr_strings[:,5], states_midwest), 3, arr_strings[:,5]) # Região centro-oeste
arr_strings[:,5] = np.where(np.isin(arr_strings[:,5], states_east), 4, arr_strings[:,5]) # Região leste

In [735]:
np.unique(arr_strings[:, 5]) # Verificar os valores únicos da sexta coluna

array(['0', '1', '2', '3', '4'], dtype='<U69')

## Convertendo o Array de Strings para Numérico

In [736]:
arr_strings # Visualização dos dados

array([['5', '1', '36', '13', '1', '1'],
       ['0', '1', '36', '5', '1', '4'],
       ['9', '1', '36', '10', '1', '4'],
       ...,
       ['6', '1', '36', '5', '1', '1'],
       ['4', '1', '36', '17', '1', '3'],
       ['12', '1', '36', '4', '0', '3']], dtype='<U69')

In [737]:
arr_strings = arr_strings.astype(int) # Converter os dados para o tipo inteiro
arr_strings # Visualização dos dados

array([[ 5,  1, 36, 13,  1,  1],
       [ 0,  1, 36,  5,  1,  4],
       [ 9,  1, 36, 10,  1,  4],
       ...,
       [ 6,  1, 36,  5,  1,  1],
       [ 4,  1, 36, 17,  1,  3],
       [12,  1, 36,  4,  0,  3]])

In [738]:
arr_strings.dtype # Tipo dos dados

dtype('int32')

## CheckPoint com Variáveis do Tipo String Limpas e Pré-Processadas

In [739]:
checkpoint_strings = checkpoint(".arquivos_DSA/dados/Checkpoint-Strings", header_strings, arr_strings) # Salvar os dados em um arquivo .npz

In [740]:
checkpoint_strings['header']

array(['issue_date', 'loan_status', 'term_months', 'sub_grade', 'verification_status', 'state_address'], dtype='<U19')

In [741]:
checkpoint_strings['data']

array([[ 5,  1, 36, 13,  1,  1],
       [ 0,  1, 36,  5,  1,  4],
       [ 9,  1, 36, 10,  1,  4],
       ...,
       [ 6,  1, 36,  5,  1,  1],
       [ 4,  1, 36, 17,  1,  3],
       [12,  1, 36,  4,  0,  3]])

In [742]:
np.array_equal(checkpoint_strings['data'], arr_strings)	

True

## Manipulando as colunas Numéricas

In [743]:
arr_numericos # Visualização dos dados

array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  , 68616520.  ,      938.57,     4679.7 ],
       [59432726.  ,    15000.  ,    15000.  , 68616520.  ,      494.86,     1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  , 68616520.  , 68616520.  ,     2185.64],
       [46154151.  , 68616520.  ,    10000.  ,       16.55,      354.3 ,     3199.4 ],
       [66055249.  ,    10000.  ,    10000.  , 68616520.  ,      309.97,      301.9 ]])

In [744]:
header_numeric # Visualização dos dados

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

In [745]:
np.isnan(arr_numericos).sum() # Contagem de valores ausentes

0

In [746]:
# para relembrar:
valor_coringa

68616520.0

In [747]:
np.isin(arr_numericos[:,0], valor_coringa) # Verificar se há valores coringa na primeira coluna

array([False, False, False, ..., False, False, False])

In [748]:
np.isin(arr_numericos[:,0], valor_coringa).sum() # Contagem de valores coringa na primeira coluna

0

Vamos criar um array de estatísticas para cada coluna numérica.

In [749]:
arr_stats = np.array([np.nanmin(dados, axis=0), media_ignorando_nan, np.nanmax(dados, axis=0)]) # Estatísticas dos dados
arr_stats # Visualização dos dados

array([[  373332.  ,         nan,     1000.  ,         nan,     1000.  ,         nan,        6.  ,       31.42,         nan,         nan,         nan,         nan,         nan,        0.  ],
       [54015809.19,         nan,    15273.46,         nan,    15311.04,         nan,       16.62,      440.92,         nan,         nan,         nan,         nan,         nan,     3143.85],
       [68616519.  ,         nan,    35000.  ,         nan,    35000.  ,         nan,       28.99,     1372.97,         nan,         nan,         nan,         nan,         nan,    41913.62]])

In [750]:
arr_stats[:, colunas_numericas] # Estatísticas das colunas numéricas

array([[  373332.  ,     1000.  ,     1000.  ,        6.  ,       31.42,        0.  ],
       [54015809.19,    15273.46,    15311.04,       16.62,      440.92,     3143.85],
       [68616519.  ,    35000.  ,    35000.  ,       28.99,     1372.97,    41913.62]])

## Pré-processamento da coluna funded_amnt

In [751]:
arr_numericos[:,2] # Visualdados dos dados da terceira coluna

array([35000., 30000., 15000., ..., 10000., 10000., 10000.])

In [752]:
arr_stats[0, colunas_numericas[2]] # valor mínimo da terceira coluna

1000.0

In [753]:
arr_numericos[:,2] = np.where(arr_numericos[:,2] == valor_coringa, arr_stats[0, colunas_numericas[2]], arr_numericos[:,2]) # Substituir os valores coringa pelo valor mínimo da terceira coluna
arr_numericos[:,2] # Visualização dos dados

array([35000., 30000., 15000., ..., 10000., 10000., 10000.])

## Pré-processamento das colunas loan_amnt, int_rate, installment e total_pymnt

In [754]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

In [755]:
for i in [1,3,4,5]:
    arr_numericos[:,i] = np.where(arr_numericos[:,i] == valor_coringa, 
                                  arr_stats[2, colunas_numericas[i]], 
                                  arr_numericos[:,i]) # Substituir os valores coringa pelos valores máximos das colunas correspondentes

arr_numericos # Visualização dos dados

array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  ,       28.99,      938.57,     4679.7 ],
       [59432726.  ,    15000.  ,    15000.  ,       28.99,      494.86,     1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  ,       28.99,     1372.97,     2185.64],
       [46154151.  ,    35000.  ,    10000.  ,       16.55,      354.3 ,     3199.4 ],
       [66055249.  ,    10000.  ,    10000.  ,       28.99,      309.97,      301.9 ]])

## Trabalhando com o segundo dataset

In [756]:
dados_cot = np.genfromtxt('.arquivos_DSA/dados/dataset2.csv',
                                delimiter=',',
                                skip_header=1,
                                autostrip=True,
                                usecols=3)
dados_cot # Visualização dos dados

array([1.13, 1.12, 1.08, 1.11, 1.1 , 1.12, 1.09, 1.13, 1.13, 1.1 , 1.06, 1.09])

In [757]:
header_strings

array(['issue_date', 'loan_status', 'term_months', 'sub_grade', 'verification_status', 'state_address'], dtype='<U19')

In [758]:
arr_strings

array([[ 5,  1, 36, 13,  1,  1],
       [ 0,  1, 36,  5,  1,  4],
       [ 9,  1, 36, 10,  1,  4],
       ...,
       [ 6,  1, 36,  5,  1,  1],
       [ 4,  1, 36, 17,  1,  3],
       [12,  1, 36,  4,  0,  3]])

In [759]:
arr_strings[:, 0] # Visualização dos dados da coluna 0 - mês

array([ 5,  0,  9, ...,  6,  4, 12])

In [760]:
exchange_rate = arr_strings[:, 0] # Dados da coluna 0 - mês
exchange_rate # Visualização dos dados

array([ 5,  0,  9, ...,  6,  4, 12])

In [761]:
for i in range(1,13):
    exchange_rate = np.where(exchange_rate == i, dados_cot[i-1], exchange_rate) # Substituir os meses pelos números correspondentes

exchange_rate # Visualização dos dados

array([1.1 , 0.  , 1.13, ..., 1.12, 1.11, 1.09])

In [762]:
exchange_rate = np.where(exchange_rate == 0, np.mean(dados_cot), exchange_rate) # Substituir os valores ausentes pela média
exchange_rate # Visualização dos dados

array([1.1 , 1.11, 1.13, ..., 1.12, 1.11, 1.09])

In [763]:
print(exchange_rate.shape)
print(arr_strings.shape)

(10000,)
(10000, 6)


In [764]:
exchange_rate = np.reshape(exchange_rate, (exchange_rate.shape[0], 1)) # Redimensionar o array
exchange_rate.shape # Visualização dos dados

(10000, 1)

In [765]:
arr_numericos = np.hstack((arr_numericos, exchange_rate)) # Adicionar a taxa de câmbio ao array numérico
arr_numericos # Visualização dos dados

array([[48010226.  ,    35000.  ,    35000.  , ...,     1184.86,     9452.96,        1.1 ],
       [57693261.  ,    30000.  ,    30000.  , ...,      938.57,     4679.7 ,        1.11],
       [59432726.  ,    15000.  ,    15000.  , ...,      494.86,     1969.83,        1.13],
       ...,
       [50415990.  ,    10000.  ,    10000.  , ...,     1372.97,     2185.64,        1.12],
       [46154151.  ,    35000.  ,    10000.  , ...,      354.3 ,     3199.4 ,        1.11],
       [66055249.  ,    10000.  ,    10000.  , ...,      309.97,      301.9 ,        1.09]])

In [766]:
header_numeric = np.concatenate((header_numeric, np.array(['exchange_rate']))) # Adicionar o nome da coluna ao array de cabeçalhos
header_numeric # Visualização dos dados

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt', 'exchange_rate'], dtype='<U19')

Vamos criar as colunas para as taxas de câmbio em USD e EURO

In [767]:
header_numeric # relembrar os dados

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt', 'exchange_rate'], dtype='<U19')

In [768]:
colunas_em_dolar = np.array([1,2,4,5]) # Colunas que estão em dólar
colunas_em_dolar # Visualização dos dados

array([1, 2, 4, 5])

In [769]:
arr_numericos.shape # Visualização dos dados

(10000, 7)

In [770]:
for i in colunas_em_dolar:
    arr_numericos = np.hstack((arr_numericos,
                               np.reshape(arr_numericos[:, i] / arr_numericos[:, 6],
                                          (arr_numericos.shape[0], 1)))) # Multiplicar as colunas em dólar pela taxa de câmbio

arr_numericos # Visualização dos dados

array([[48010226.  ,    35000.  ,    35000.  , ...,    31933.3 ,     1081.04,     8624.69],
       [57693261.  ,    30000.  ,    30000.  , ...,    27132.46,      848.86,     4232.39],
       [59432726.  ,    15000.  ,    15000.  , ...,    13326.3 ,      439.64,     1750.04],
       ...,
       [50415990.  ,    10000.  ,    10000.  , ...,     8910.3 ,     1223.36,     1947.47],
       [46154151.  ,    35000.  ,    10000.  , ...,     8997.4 ,      318.78,     2878.63],
       [66055249.  ,    10000.  ,    10000.  , ...,     9145.8 ,      283.49,      276.11]])

In [771]:
arr_numericos.shape # Visualização dos dados

(10000, 11)

In [772]:
header_additional = np.array([nome_coluna + '_EUR' for nome_coluna in header_numeric[colunas_em_dolar]]) # Criação dos nomes das novas colunas
header_additional # Visualização dos dados

array(['loan_amnt_EUR', 'funded_amnt_EUR', 'installment_EUR', 'total_pymnt_EUR'], dtype='<U15')

In [773]:
header_numeric = np.concatenate((header_numeric, header_additional)) # Adicionar os novos nomes ao array de cabeçalhos
header_numeric # Visualização dos dados

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt', 'exchange_rate', 'loan_amnt_EUR', 'funded_amnt_EUR', 'installment_EUR', 'total_pymnt_EUR'], dtype='<U19')

In [774]:
header_numeric[colunas_em_dolar] = np.array([nome_coluna + '_USD' for nome_coluna in header_numeric[colunas_em_dolar]]) # Alterar os nomes das colunas em dólar
header_numeric # Visualização dos dados

array(['id', 'loan_amnt_USD', 'funded_amnt_USD', 'int_rate', 'installment_USD', 'total_pymnt_USD', 'exchange_rate', 'loan_amnt_EUR', 'funded_amnt_EUR', 'installment_EUR', 'total_pymnt_EUR'],
      dtype='<U19')

In [775]:
colunas_index_order = [0,1,7,2,8,3,4,9,5,10,6] # Ordem das colunas
header_numeric = header_numeric[colunas_index_order] # Alterar a ordem das colunas
header_numeric # Visualização dos dados

array(['id', 'loan_amnt_USD', 'loan_amnt_EUR', 'funded_amnt_USD', 'funded_amnt_EUR', 'int_rate', 'installment_USD', 'installment_EUR', 'total_pymnt_USD', 'total_pymnt_EUR', 'exchange_rate'],
      dtype='<U19')

In [776]:
arr_numericos = arr_numericos[:, colunas_index_order] # Alterar a ordem das colunas

## Pré-processamento da coluna int_rate

In [777]:
arr_numericos[:,5] # Visualização dos dados da sexta coluna

array([13.33, 28.99, 28.99, ..., 28.99, 16.55, 28.99])

In [778]:
arr_numericos[:,5] = arr_numericos[:,5] / 100 # Dividir a sexta coluna por 100
arr_numericos[:,5] # Visualização dos dados

array([0.13, 0.29, 0.29, ..., 0.29, 0.17, 0.29])

## CheckPoint com Variáveis Numéricas Limpas e Pré-Processadas

In [779]:
checkpoint_numericos = checkpoint(".arquivos_DSA/dados/Checkpoint-Numeric", 
                                  header_numeric, arr_numericos) # Salvar os dados em um arquivo .npz
checkpoint_numericos['header'], checkpoint_numericos['data'] # Visualização dos dados

(array(['id', 'loan_amnt_USD', 'loan_amnt_EUR', 'funded_amnt_USD', 'funded_amnt_EUR', 'int_rate', 'installment_USD', 'installment_EUR', 'total_pymnt_USD', 'total_pymnt_EUR', 'exchange_rate'],
       dtype='<U19'),
 array([[48010226.  ,    35000.  ,    31933.3 , ...,     9452.96,     8624.69,        1.1 ],
        [57693261.  ,    30000.  ,    27132.46, ...,     4679.7 ,     4232.39,        1.11],
        [59432726.  ,    15000.  ,    13326.3 , ...,     1969.83,     1750.04,        1.13],
        ...,
        [50415990.  ,    10000.  ,     8910.3 , ...,     2185.64,     1947.47,        1.12],
        [46154151.  ,    35000.  ,    31490.9 , ...,     3199.4 ,     2878.63,        1.11],
        [66055249.  ,    10000.  ,     9145.8 , ...,      301.9 ,      276.11,        1.09]]))

In [780]:
print(checkpoint_strings['data'].shape)
print(checkpoint_numericos['data'].shape)

(10000, 6)
(10000, 11)


In [781]:
df_final = np.hstack((checkpoint_numericos['data'],
                      checkpoint_strings['data'])) # Combinar os arrays de strings e numéricos
df_final # Visualização dos dados

array([[48010226.  ,    35000.  ,    31933.3 , ...,       13.  ,        1.  ,        1.  ],
       [57693261.  ,    30000.  ,    27132.46, ...,        5.  ,        1.  ,        4.  ],
       [59432726.  ,    15000.  ,    13326.3 , ...,       10.  ,        1.  ,        4.  ],
       ...,
       [50415990.  ,    10000.  ,     8910.3 , ...,        5.  ,        1.  ,        1.  ],
       [46154151.  ,    35000.  ,    31490.9 , ...,       17.  ,        1.  ,        3.  ],
       [66055249.  ,    10000.  ,     9145.8 , ...,        4.  ,        0.  ,        3.  ]])

In [782]:
np.isnan(df_final).sum() # Contagem de valores ausentes

0

In [783]:
header_full = np.concatenate((checkpoint_numericos['header'], 
                              checkpoint_strings['header'])) # Combinar os arrays de cabeçalhos
header_full # Visualização dos dados

array(['id', 'loan_amnt_USD', 'loan_amnt_EUR', 'funded_amnt_USD', 'funded_amnt_EUR', 'int_rate', 'installment_USD', 'installment_EUR', 'total_pymnt_USD', 'total_pymnt_EUR', 'exchange_rate',
       'issue_date', 'loan_status', 'term_months', 'sub_grade', 'verification_status', 'state_address'], dtype='<U19')

In [784]:
df_final = df_final[np.argsort(df_final[:,0])] # Ordenar os dados por ID
df_final # Visualização dos dados

array([[  373332.  ,     9950.  ,     9038.08, ...,       21.  ,        0.  ,        1.  ],
       [  575239.  ,    12000.  ,    10900.2 , ...,       25.  ,        1.  ,        2.  ],
       [  707689.  ,    10000.  ,     8924.3 , ...,       13.  ,        1.  ,        0.  ],
       ...,
       [68614880.  ,     5600.  ,     5121.65, ...,        8.  ,        1.  ,        1.  ],
       [68615915.  ,     4000.  ,     3658.32, ...,       10.  ,        1.  ,        2.  ],
       [68616519.  ,    21600.  ,    19754.93, ...,        3.  ,        0.  ,        2.  ]])

In [785]:
np.argsort(df_final[:,0]) # Visualização dos dados

array([   0,    1,    2, ..., 9997, 9998, 9999], dtype=int64)

## Gravando o dataset final limpo e pré-processado

In [786]:
df_final = np.vstack((header_full, df_final)) # Adicionar os cabeçalhos
df_final # Visualização dos dados

array([['id', 'loan_amnt_USD', 'loan_amnt_EUR', ..., 'sub_grade', 'verification_status', 'state_address'],
       ['373332.0', '9950.0', '9038.082814338286', ..., '21.0', '0.0', '1.0'],
       ['575239.0', '12000.0', '10900.20037910145', ..., '25.0', '1.0', '2.0'],
       ...,
       ['68614880.0', '5600.0', '5121.647851612413', ..., '8.0', '1.0', '1.0'],
       ['68615915.0', '4000.0', '3658.319894008867', ..., '10.0', '1.0', '2.0'],
       ['68616519.0', '21600.0', '19754.927427647883', ..., '3.0', '0.0', '2.0']], dtype='<U32')

In [787]:
np.savetxt('.arquivos_DSA/dados/dataset_limpo_preprocessado.csv', # local e nome para salvar o arquivo
           df_final, # dados a serem salvos
           delimiter=',', # delimitador
           fmt='%s') # formato dos dados